FROM python:3.11

# host container
# add main.py to the container
ADD main.py . 
# installing with pip
RUN pip install plotly_express dash

EXPOSE 8050

# run main.py with the CMD command
CMD ["python", "./main.py"]

